{
  "formatVersion": "1.1",
  "component": {
    "group": "app.nekogram.tcp2ws",
    "module": "tcp2ws",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tcp2ws-1.3.1.aar",
          "url": "tcp2ws-1.3.1.aar",
          "size": 16631,
          "sha512": "a85292d60e0216da9bd3a6ee7d30061207c078b6d48124317a9f100cc0fbc325df36225f1618aeff5d56bdfa79a11fbb365b523b6bffe2a665e094ab372fbe9e",
          "sha256": "53d3ed83c061b5e773c1635ed2f2cd5dc5297f2b5c7f79d1d557b4b1442430bd",
          "sha1": "dae521955297c7f33252fffad202a2435800bd1f",
          "md5": "210e4d49f9f7f4a242e414808ee222a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lsposed.lsparanoid",
          "module": "core",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        }
      ],
      "files": [
        {
          "name": "tcp2ws-1.3.1.aar",
          "url": "tcp2ws-1.3.1.aar",
          "size": 16631,
          "sha512": "a85292d60e0216da9bd3a6ee7d30061207c078b6d48124317a9f100cc0fbc325df36225f1618aeff5d56bdfa79a11fbb365b523b6bffe2a665e094ab372fbe9e",
          "sha256": "53d3ed83c061b5e773c1635ed2f2cd5dc5297f2b5c7f79d1d557b4b1442430bd",
          "sha1": "dae521955297c7f33252fffad202a2435800bd1f",
          "md5": "210e4d49f9f7f4a242e414808ee222a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tcp2ws-1.3.1-javadoc.jar",
          "url": "tcp2ws-1.3.1-javadoc.jar",
          "size": 275660,
          "sha512": "a30c202281fa42294ccc06d957b0bce61eec6461f9ff350d0d8b67f02f7d1599efd1978eabc531dea4845fe1bd24460475ea31852b48ec3376adbfb4ac644024",
          "sha256": "4cbb54ab8b9aab4814b160ec2054d2c93ba76ba51f1fcfe220580fe25b48ebf1",
          "sha1": "01d19d053482fd201f8e532f2560eca864af3ea9",
          "md5": "d16821a40c8668968a7f7ae760fd450e"
        }
      ]
    }
  ]
}
